admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout

admin.user.list:
    path:     /admin/user
    defaults: { _controller: AdminBundle:User:userList }
