admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout

user_list:
    path:     /userList/{page}
    defaults: { _controller: AdminBundle:User:userList }
