api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

logout:
    path: /logout

root:
    path: /
    defaults:
        _controller: AdminBundle:Security:login
        permanent: true
api:
   resource: "@ApiBundle/Controller/"
   type:      annotation
   prefix:    /api
