# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_MANAGER: ROLE_USER
        ROLE_ADMIN: [ROLE_MANAGER, ROLE_USER]

    providers:
        db_provider:
            entity: { class: AppBundle:User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_api:
            pattern:  ^/api/login$
            anonymous:  ~
        api:
            pattern: ^/api/
            stateless: true
            guard:
                authenticators:
                    - ApiBundle\Security\TokenAuthenticator
        main:
            pattern:  ^/
            form_login:
                login_path: /admin/login
                check_path: /admin/login
                default_target_path: /admin
            logout: true
            anonymous: ~
            context: primary_auth

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
