security:

    encoders:
        AppBundle\Entity\User:
            algorithm: plaintext

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:  ^/
            logout:
                path:   /logout
                target: /

            anonymous: ~
            http_basic: ~
            provider: our_db_provider

    access_control:
            - { path: ^/user, roles: ROLE_USER }
            - { path: ^/manager, roles: ROLE_MANAGER }
            - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_MANAGER: ROLE_USER
        ROLE_ADMIN: [ROLE_MANAGER, ROLE_USER]
