# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: plaintext

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:  ^/
            logout:
                path:   /logout
                target: /login
            form_login:
                login_path: /login
                check_path: /login
                always_use_default_target_path: true
                default_target_path: /admin

            anonymous: ~
            provider: our_db_provider

    access_control:
            - { path: ^/user, roles: ROLE_USER }
            - { path: ^/manager, roles: ROLE_MANAGER }
            - { path: ^/admin, roles: ROLE_ADMIN }

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    encoders:
        AppBundle\Entity\User: bcrypt
    role_hierarchy:
        ROLE_MANAGER: ROLE_USER
        ROLE_ADMIN: [ROLE_MANAGER, ROLE_USER]
