parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AdminBundle\Validator\Constraints\UniqueUserValidator:
        autowire: true

    AdminBundle\Validator\Constraints\UniqueCategoryValidator:
        autowire: true
