parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository}'

    AdminBundle\:
        resource: '../../src/AdminBundle/*'
        exclude: '../../src/AdminBundle/{Entity,Repository}'

    ApiBundle\:
        resource: '../../src/ApiBundle/*'
        exclude: '../../src/ApiBundle/{Entity,Repository}'

    AdminBundle\Controller\:
        resource: '../../src/AdminBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    ApiBundle\Controller\:
        resource: '../../src/ApiBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
