parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AdminBundle\Validator\UserValidator:
        arguments: ["@doctrine.orm.entity_manager"]
