services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ApiBundle\Handler\LoginHandler:
        public: true
#        arguments:
#            - '@doctrine.orm.entity_manager'

