services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ApiBundle\:
        resource: '../../*'

    ApiBundle\Handler\RegistrationHandler:
        public: true
